services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/feroxfoxxo/compress.lol:latest
    container_name: compress-lol
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: "3000"
      HOST: "0.0.0.0"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:3000/').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  default:
    name: compress-lol
    driver: bridge
